"""Scene-medium attribution helpers."""

from .medium_explainability import (
    MediumExplainabilitySupport,
    accumulation_clearance_amplifier,
    budgeted_capacity_loss,
    build_residual_gated_halo_support,
    build_route_capacity_support,
    build_training_routed_prediction,
    clear_proxy_chroma_loss,
    clear_proxy_luma_budget_loss,
    compute_far_depth_support,
    compute_image_structure_support,
    compute_medium_explainability,
    core_zero_capacity_loss,
    rgb_luma_budget_loss,
    support_coverage_stats,
    weighted_rgb_l1,
)
from .tacmd import (
    TacmdBsState,
    TacmdTailEvidence,
    bs_band_loss,
    bs_convergence_losses,
    bs_state_stats,
    build_bs_state,
    build_counterfactual_bs,
    combine_tail_anchor,
    compute_tail_evidence,
    counterfactual_chroma_loss,
    tail_anchor_losses,
)

__all__ = [
    "MediumExplainabilitySupport",
    "TacmdBsState",
    "TacmdTailEvidence",
    "accumulation_clearance_amplifier",
    "bs_band_loss",
    "bs_convergence_losses",
    "bs_state_stats",
    "build_bs_state",
    "build_counterfactual_bs",
    "budgeted_capacity_loss",
    "build_residual_gated_halo_support",
    "build_route_capacity_support",
    "build_training_routed_prediction",
    "combine_tail_anchor",
    "clear_proxy_chroma_loss",
    "clear_proxy_luma_budget_loss",
    "compute_far_depth_support",
    "compute_image_structure_support",
    "compute_medium_explainability",
    "compute_tail_evidence",
    "core_zero_capacity_loss",
    "counterfactual_chroma_loss",
    "rgb_luma_budget_loss",
    "support_coverage_stats",
    "tail_anchor_losses",
    "weighted_rgb_l1",
]
